# -*- coding: utf-8 -*-
"""MediDASH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhKDR-EJg6ffM4_Uf1NA3RnWZ3edkJ-C
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import plotly.express as px

# Set Page Configuration
st.set_page_config(page_title="AI Hospital Optimization Dashboard", layout="wide")

# Sidebar Navigation
st.sidebar.title("Navigation")
page = st.sidebar.radio("Select a Section:", [
    "AI Adoption Overview",
    "Before vs After AI Impact",
    "AI Model Implementation Roadmap",
    "Secure Data Sharing & AIaaS Cost Analysis"
])

# AI Adoption Overview
if page == "AI Adoption Overview":
    st.title("📈 AI Adoption in Hospital Diagnostics")
    years = ["Year 1", "Year 2", "Year 3", "Year 4", "Year 5"]
    adoption_rate = [15, 30, 50, 70, 85]
    fig = px.line(x=years, y=adoption_rate, markers=True, title="AI Adoption Growth Over Time")
    fig.update_layout(xaxis_title="Years", yaxis_title="AI Adoption (%)")
    st.plotly_chart(fig)

# Before vs After AI Impact
elif page == "Before vs After AI Impact":
    st.title("📊 Before vs. After AI Implementation")

    categories = ["ICU Bed Availability", "Doctor Utilization", "Wait Time Reduction"]
    before_ai = [60, 73, 55]
    after_ai = [90, 88, 80]
    df = pd.DataFrame({"Category": categories, "Before AI": before_ai, "After AI": after_ai})
    df_melted = df.melt(id_vars=["Category"], var_name="AI Impact", value_name="Percentage")
    fig = px.bar(df_melted, x="Category", y="Percentage", color="AI Impact", barmode="group",
                 title="Hospital Workflow Performance Before vs After AI")
    st.plotly_chart(fig)

# AI Model Implementation Roadmap
elif page == "AI Model Implementation Roadmap":
    st.title("🛠 AI Implementation Phases")
    roadmap = {
        "Phase 1": "Deploy AI in low-risk areas (Radiology, Pathology).",
        "Phase 2": "Provide training & success tracking for AI reliability.",
        "Phase 3": "Expand AI to high-risk departments (ER, Oncology).",
        "Phase 4": "Monitor AI compliance & regulatory approval."
    }
    st.table(pd.DataFrame(roadmap.items(), columns=["Phase", "Description"]))

# Secure Data Sharing & AIaaS Cost Analysis
elif page == "Secure Data Sharing & AIaaS Cost Analysis":
    st.title("🔐 Secure Data Sharing & AIaaS Cost Analysis")

    cost_model = ["On-Premise AI", "Cloud AI-as-a-Service"]
    cost_savings = ["Higher initial cost, long-term savings", "Lower cost, scalable, requires cloud dependency"]
    df_cost = pd.DataFrame({"AI Model": cost_model, "Cost Consideration": cost_savings})
    st.table(df_cost)

    st.markdown("### **Blockchain-Based Secure Data Sharing**")
    st.write("Blockchain ensures secure hospital data sharing and regulatory compliance.")

    features = ["WBC Count", "Tumor Size", "Scan Intensity", "Patient Age", "Heart Rate"]
    ai_prediction = [0.85, 0.76, 0.90, 0.68, 0.72]
    fig, ax = plt.subplots(figsize=(7, 5))
    sns.heatmap(np.array(ai_prediction).reshape(1, -1), annot=True, cmap="coolwarm", xticklabels=features,
                yticklabels=["AI Feature Importance"], linewidths=0.5)
    ax.set_title("SHAP Explanation Heatmap: AI Feature Importance", fontsize=14, fontweight="bold")
    st.pyplot(fig)

st.sidebar.markdown("---")
st.sidebar.write("🚀 AI-Powered Hospital Optimization Dashboard")